### ISSUE TITLE
None of any code working

### ISSUE THREAD

**Issue by bakamaru** [a1q123456/Harmonic#5]
I've tried and run ffmpeg command to push stream but none of then working.why?

**Comment by a1q123456** [comment]
you can try tag 1.0 or master branch that will work

**Comment by a1q123456** [comment]
btw you need to push to url rtmp://<ip>/Living/<streamName> for master and rtmp://<ip>/app/<streamName> for tag 0.0.1

**Comment by bakamaru** [comment]
yes now its working.Thanks for the help but please add documentation properly.

**Comment by a1q123456** [comment]
Okay
